version: '3.8'
services: 
    api-service:
        build: .
        command: flask run --host=0.0.0.0 --port=8080
        volumes: 
            - .:/code
        ports: 
            - 8080:8080
        environment: 
            PORT: 8080
            FLASK_DEBUG: 1
